apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: OmniaDataCatalogApi
spec:
  build:
  environments:
    - name: feature
      build:
        from: feature/*
    - name: development
      build:
        from: master 
  components:
    - name: OmniaDataCatalogApi      
      dockerfileName: Dockerfile      
      ports:
        - name: http
          port: 3000
      public: true
      replicas: 1
