apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: HelloRadix
spec:
  build:
  environments:
    - name: feature
      build:
        from: feature/*
    - name: development
      build:
        from: master
    - name: production
      build:
        from: release
  components:
    - name: helloradix
      variables:
        RADIX_PUBLIC_DOMAIN_NAME: helloradix-helloradix-feature.playground.radix.equinor.com/swagger/index.html
      dockerfileName: Dockerfile
      image: swagger/index.html
      ports:
        - name: http
          port: 3000
      public: true
      replicas: 1
